<?php

/**
* Implements hook_help().
*/
function sydneyzufang_help($path, $arg) {
  if ($path == 'admin/help#sydneyzufang') {
    return t('Sydney Zufang module');
  }
}

/**
 * Implements hook_page_alter()
 */
function sydneyzufang_page_alter(&$page) {
  // remove front page "no content" message
  if (drupal_is_front_page()) {
    unset($page['content']['system_main']);
  }
}

/**
 * Implement hook_form_alter()
 * 
 * @param type $form
 * @param type $form_state
 * @param type $form_id
 */
function sydneyzufang_form_alter(&$form, &$form_state, $form_id) {
    // exposed view search form
    if (isset($form['#id']) && $form['#id'] == 'views-exposed-form-rental-item-search-search-result-list') {
      // placeholder
      $form['submit']['#value'] = '搜索房源';
      if (module_exists('placeholder')) {
        $form['search_api_views_fulltext']['#placeholder'] = '请输入地区名，或者任意关键字';
      }
      // redirect to suburb search result
      if (isset($form_state['input']) && !empty($form_state['input']) && isset($form_state['input']['search_api_views_fulltext'])) {
        $keyword = ucfirst(trim($form_state['input']['search_api_views_fulltext']));
        if (in_array($keyword, Utility::getInstance()->getSetting('sydneytoday->suburbs'))) {
          
          $suburbs = array_flip($form['field_rental_suburb']['#options']);
          $suburb_id = isset($suburbs[$keyword]) ? $suburbs[$keyword] : null;
          if (!is_null($suburb_id)) {
            // clear full text input
            unset($form_state['input']['search_api_views_fulltext']);
            // clear property type
            unset($form_state['input']['field_rental_property_type']);
            // clear rental type
            unset($form_state['input']['field_rental_rental_type']);
            // set suburb
            $form_state['input']['field_rental_suburb'] = $suburb_id;
//            echo "<pre>";
//            print_r($form_state['input']['field_rental_suburb']);
//            die("</pre>");
          }

        }
      }
    }
    
    
    // alter node creatation form, only when it is not backend theme
    if ($form_id == 'rental_node_form' && path_to_theme() != 'themes/seven') {
      unset($form['field_rental_near_by_facilities_']);
      unset($form['field_rental_facilities_']);
      unset($form['field_rental_comment']);
      unset($form['field_rental_url']);

      if (module_exists('placeholder')) {
  //      echo "<pre>";
  //      print_r(($form['actions']));
  //      die("</pre>");
        $form['title']['#title'] = '标题';
        $form['actions']['submit']['#value'] = '立刻发布';
        $form['title']['#placeholder'] = '如: 宽敞主卧招安静女生';
        $form['field_rental_suburb']['und']['#placeholder'] = '如: Ashfield';
        $form['field_rental_price']['und'][0]['value']['#placeholder'] = '周租金(数字),如: 250';
        $form['body']['und'][0]['value']['#placeholder'] = '输入任何您希望租客了解的信息';
        $form['field_rental_contact']['und'][0]['value']['#placeholder'] = '您的姓名';
        $form['field_rental_mobile']['und'][0]['value']['#placeholder'] = '您的手机号码';
        $form['field_rental_phone']['und'][0]['value']['#placeholder'] = '您的座机号码';
        $form['field_rental_qq']['und'][0]['value']['#placeholder'] = '您的QQ号码';
        $form['field_rental_address']['und'][0]['value']['#placeholder'] = '如: 43/11 Pitt Street, Sydney';
        $form['field_rental_email']['und'][0]['value']['#placeholder'] = '您的邮箱地址';
      }
    }
}

/**
 * Implement hook_block_view
 * 
 * @param type $delta
 */
//function sydneyzufang_block_view_alter (&$data, $block) {
//  // change exposed view search bar markup. move the submit button up
//}

function _get_request_var($key) {
  return (isset($_REQUEST[$key]) && !empty($_REQUEST[$key])) ? strip_tags($_REQUEST[$key]) : null;
}