<?php
/**
 * Implement hook_init()
 */
function jOverlay_init() {
  global $theme;
  if ($theme != variable_get('admin_theme')) {
    drupal_add_css(drupal_get_path('module', 'jOverlay') . '/jOverlay.css', array('group' => CSS_DEFAULT, 'every_page' => TRUE));
    drupal_add_js(drupal_get_path('module', 'jOverlay') . '/jOverlay.js', array('group' => JS_DEFAULT, 'every_page' => TRUE));
  }
}