cache_folder: public://cache

dingtie_messages:
  - Please contact
  - If you want further info, feel free to call me
  - Let me know if you are interested
  - Don't miss out
  - Thanks for contacting
  - Contact if interested
  - Good stuff, don't miss out
  - Please call me in you are interested
  - Let me know if you want it
  - Very good opportunity
  - Contact please
  - Call for further info
  - Call me ~
  - Good stuff. Don't miss out
  - Please see the contact at the bottom of the post
  - Let me know if interested
  - You know how to contact me
  - Act quick, or you'll miss it
  - You know it is good stuff
  - I'll be here, so call me
  - Call me please
