cache_folder: public://cache

dingtie_messages:
  - Please contact
  - If you want further info, feel free to call me
  - Let me know if you are interested
  - Don't miss out
  - Up up ~~
  - Contact if interested
  - Good stuff, don't miss out
  - You know you want it
  - Just do it
  - Hello there
  - Contact please
  - Call for further info
  - Call me ~
  - Don't sink..
  - Up up, happy post
  - Let me know if interested
  - You know how to contact me
  - Act quick, or you'll miss it
  - You know it is good stuff
  - I'll be here, so call me
  - Happy business