sydneytoday:
  list_url: 
    - http://www.sydneytoday.com/list.php?fid=12

  cron_image_store: public://cronimgs
  
  img_textfields:
    - field_rental_mobile
    - field_rental_phone
    - field_rental_email
    
  suburbs:
    - Abbotsbury
    - Abbotsford
    - Alexandria
    - Alfords Point
    - Allambie Heights
    - Allawah
    - Annandale
    - Annangrove
    - Arcadia
    - Arncliffe
    - Arndell Park
    - Artarmon
    - Ashbury
    - Ashcroft
    - Ashfield
    - Asquith
    - Auburn
    - Austral
    - Avalon
    - Avalon Beach
    - Balgowlah
    - Balgowlah Heights
    - Balmain
    - Balmain East
    - Bangor
    - Banksia
    - Banksmeadow
    - Bankstown
    - Bankstown North
    - Barden Ridge
    - Bardia
    - Bardwell Park
    - Bardwell Valley
    - Bass Hill
    - Baulkham Hills
    - Bayview
    - Beacon Hill
    - Beaconsfield
    - Beaumont Hills
    - Beecroft
    - Belfield
    - Bella Vista
    - Bellevue Hill
    - Belmore
    - Belrose
    - Berala
    - Berowra
    - Berowra Creek
    - Berowra Heights
    - Berowra Waters
    - Berrilee
    - Beverley Park
    - Beverly Hills
    - Bexley
    - Bexley North
    - Bexley South
    - Bidwill
    - Bilgola
    - Birchgrove
    - Birrong
    - Blacktown
    - Blakehurst
    - Bligh Park
    - Bondi
    - Bondi Beach
    - Bondi Junction
    - Bonnet Bay
    - Bonnyrigg
    - Bonnyrigg Heights
    - Boronia Park
    - Bossley Park
    - Botany
    - Breakfast Point
    - Brighton-le-sands
    - Bringelly
    - Broadway
    - Bronte
    - Brookvale
    - Bundeena
    - Burraneer
    - Burwood
    - Burwood Heights
    - Busby
    - Cabarita
    - Cabramatta
    - Cabramatta West
    - Camellia
    - Cammeray
    - Camperdown
    - Campsie
    - Canada Bay
    - Canley Heights
    - Canley Vale
    - Canterbury
    - Caringbah
    - Caringbah South
    - Carlingford
    - Carlton
    - Carnes Hill
    - Carramar
    - Carss Park
    - Cartwright
    - Castle Cove
    - Castle Hill
    - Castlecrag
    - Casula
    - Cattai
    - Cecil Hills
    - Cecil Park
    - Centennial Park
    - Chatswood
    - Chatswood West
    - Cheltenham
    - Cherrybrook
    - Chester Hill
    - Chifley
    - Chippendale
    - Chipping Norton
    - Chiswick
    - Chullora
    - Church Point
    - Clareville
    - Clemton Park
    - Clontarf
    - Clovelly
    - Clyde
    - Coasters Retreat
    - Colebee
    - Collaroy
    - Collaroy Beach
    - Collaroy Plateau West
    - Colyton
    - Como
    - Concord
    - Concord West
    - Condell Park
    - Connells Point
    - Constitution Hill
    - Coogee
    - Cornwallis
    - Cottage Point
    - Cowan
    - Cremorne
    - Cremorne Point
    - Cromer
    - Cronulla
    - Crows Nest
    - Croydon
    - Croydon Park
    - Cumberland Reach
    - Curl Curl
    - Daceyville
    - Darling Point
    - Darlinghurst
    - Darlington
    - Davidson
    - Dawes Point
    - Dean Park
    - Dee Why
    - Denistone
    - Denistone East
    - Denistone West
    - Dolans Bay
    - Dolls Point
    - Doonside
    - Double Bay
    - Dover Heights
    - Drummoyne
    - Duffys Forest
    - Dulwich Hill
    - Dundas
    - Dundas Valley
    - Dural
    - Earlwood
    - East Hills
    - East Killara
    - East Lindfield
    - East Ryde
    - Eastern Creek
    - Eastgardens
    - Eastlakes
    - Eastwood
    - Edensor Park
    - Edgecliff
    - Edmondson Park
    - Elanora Heights
    - Elizabeth Bay
    - Elvina Bay
    - Enfield
    - Engadine
    - Enmore
    - Epping
    - Ermington
    - Erskine Park
    - Erskineville
    - Eveleigh
    - Fairfield
    - Fairfield East
    - Fairfield Heights
    - Fairfield West
    - Fairlight
    - Fiddletown
    - Five Dock
    - Forest Glen
    - Forest Lodge
    - Forestville
    - Frenchs Forest
    - Freshwater
    - Galston
    - Georges Hall
    - Girraween
    - Gladesville
    - Glebe
    - Glendenning
    - Glenfield
    - Glenhaven
    - Glenorie
    - Glenwood
    - Gordon
    - Granville
    - Grays Point
    - Great Mackerel Beach
    - Green Valley
    - Greenacre
    - Greenfield Park
    - Greenwich
    - Greystanes
    - Guildford
    - Guildford West
    - Gymea
    - Gymea Bay
    - Haberfield
    - Hammondville
    - Harbord
    - Harris Park
    - Hassall Grove
    - Haymarket
    - Heathcote
    - Hebersham
    - Heckenberg
    - Henley
    - Hillsdale
    - Hinchinbrook
    - Holroyd
    - Holsworthy
    - Homebush
    - Homebush Bay
    - Homebush West
    - Horningsea Park
    - Hornsby
    - Hornsby Heights
    - Horsley Park
    - Hoxton Park
    - Hunters Hill
    - Huntingwood
    - Huntleys Cove
    - Huntleys Point
    - Hurlstone Park
    - Hurstville
    - Hurstville Grove
    - Illawong
    - Ingleside
    - Jannali
    - Kangaroo Point
    - Kareela
    - Kellyville
    - Kellyville Ridge
    - Kemps Creek
    - Kensington
    - Kenthurst
    - Killara
    - Killarney Heights
    - Kings Langley
    - Kings Park
    - Kingsford
    - Kingsgrove
    - Kirrawee
    - Kirribilli
    - Kogarah
    - Kogarah Bay
    - Kurnell
    - Kurraba Point
    - Kyeemagh
    - Kyle Bay
    - La Perouse
    - Lakemba
    - Lalor Park
    - Lane Cove
    - Lane Cove North
    - Lane Cove West
    - Lansdowne
    - Lansvale
    - Lavender Bay
    - Leets Vale
    - Leichhardt
    - Leppington
    - Lewisham
    - Liberty Grove
    - Lidcombe
    - Lilli Pilli
    - Lilyfield
    - Lindfield
    - Lindfield West
    - Linley Point
    - Little Bay
    - Liverpool
    - Loftus
    - Longueville
    - Lovett Bay
    - Lucas Heights
    - Lugarno
    - Lurnea
    - Macquarie Fields
    - Macquarie Park
    - Maianbar
    - Malabar
    - Manly
    - Manly Vale
    - Marayong
    - Maroota
    - Maroubra
    - Marrickville
    - Marsfield
    - Mascot
    - Matraville
    - Mays Hill
    - Mcgraths Hill
    - Mcmahons Point
    - Meadowbank
    - Melrose Park
    - Menai
    - Merrylands
    - Merrylands West
    - Middle Cove
    - Middle Dural
    - Middleton Grange
    - Miller
    - Millers Point
    - Milperra
    - Milsons Point
    - Minchinbury
    - Miranda
    - Mona Vale
    - Monterey
    - Moore Park
    - Moorebank
    - Morning Bay
    - Mortdale
    - Mortlake
    - Mosman
    - Mount Colah
    - Mount Druitt
    - Mount Kuring-gai
    - Mount Lewis
    - Mount Lewis
    - Mount Pritchard
    - Mount Vernon
    - Mulgrave
    - Naremburn
    - Narrabeen
    - Narraweena
    - Narwee
    - Neutral Bay
    - Newington
    - Newport
    - Newport Beach
    - Newtown
    - Normanhurst
    - North Balgowlah
    - North Bondi
    - North Curl Curl
    - North Epping
    - North Manly
    - North Narrabeen
    - North Parramatta
    - North Rocks
    - North Ryde
    - North Strathfield
    - North Sydney
    - North Turramurra
    - North Wahroonga
    - North Willoughby
    - Northbridge
    - Northmead
    - Northwood
    - Oakhurst
    - Oatlands
    - Oatley
    - Old Guildford
    - Old Toongabbie
    - Oxford Falls
    - Oyster Bay
    - Paddington
    - Padstow
    - Padstow Heights
    - Pagewood
    - Palm Beach
    - Panania
    - Parklea
    - Parramatta
    - Peakhurst
    - Peakhurst Heights
    - Pemulwuy
    - Pendle Hill
    - Pennant Hills
    - Penshurst
    - Petersham
    - Phillip Bay
    - Picnic Point
    - Pitt Town
    - Pitt Town Bottoms
    - Pleasure Point
    - Plumpton
    - Point Piper
    - Port Botany
    - Port Hacking
    - Potts Hill
    - Potts Point
    - Prairiewood
    - Prestons
    - Prospect
    - Punchbowl
    - Putney
    - Pymble
    - Pyrmont
    - Queens Park
    - Queenscliff
    - Ramsgate
    - Ramsgate Beach
    - Randwick
    - Redfern
    - Regents Park
    - Revesby
    - Revesby Heights
    - Rhodes
    - Riverview
    - Riverwood
    - Rockdale
    - Rodd Point
    - Rooty Hill
    - Rose Bay
    - Rose Bay North
    - Rosebery
    - Rosehill
    - Roselands
    - Roseville
    - Roseville Chase
    - Rossmore
    - Round Corner
    - Rouse Hill
    - Rozelle
    - Rushcutters Bay
    - Russell Lea
    - Rydalmere
    - Ryde
    - Sackville North
    - Sadleir
    - Sandringham
    - Sandy Point
    - Sans Souci
    - Scheyville
    - Schofields
    - Scotland Island
    - Seaforth
    - Sefton
    - Seven Hills
    - Silverwater
    - Smithfield
    - South Coogee
    - South Granville
    - South Hurstville
    - South Maroota
    - South Turramurra
    - South Wentworthville
    - South Windsor
    - Spit Junction
    - St Clair
    - St Ives
    - St Ives Chase
    - St Johns Park
    - St Leonards
    - St Peters
    - Stanhope Gardens
    - Stanmore
    - Strathfield
    - Strathfield South
    - Summer Hill
    - Surry Hills
    - Sutherland
    - Sydenham
    - Sydney
    - Sylvania
    - Sylvania Waters
    - Tamarama
    - Taren Point
    - Taylors Point
    - Telopea
    - Tempe
    - Tennyson Point
    - Terrey Hills
    - The Ponds
    - The Rocks
    - Thornleigh
    - Tolwong
    - Toongabbie
    - Turramurra
    - Turrella
    - Ultimo
    - Vaucluse
    - Villawood
    - Voyager Point
    - Wahroonga
    - Waitara
    - Wakeley
    - Wareemba
    - Warrawee
    - Warriewood
    - Warwick Farm
    - Waterfall
    - Waterloo
    - Watsons Bay
    - Wattle Grove
    - Waverley
    - Waverton
    - Wentworth Point
    - Wentworthville
    - West Hoxton
    - West Pennant Hills
    - West Pymble
    - West Ryde
    - Westleigh
    - Westmead
    - Wetherill Park
    - Whalan
    - Whale Beach
    - Wheeler Heights
    - Wiley Park
    - Willoughby
    - Willoughby East
    - Willoughby North
    - Windsor
    - Winston Hills
    - Wolli Creek
    - Wollstonecraft
    - Woodcroft
    - Woodpark
    - Woollahra
    - Woolloomooloo
    - Woolooware
    - Woolwich
    - Woronora
    - Woronora Heights
    - Yagoona
    - Yarrawarrah
    - Yennora
    - Yowie Bay
    - Zetland

