<?php

function mobile_adaptive_menu() {
  $items = array();
  $items['mobile-adaptive'] = array(
    'page callback' => 'mobile_adaptive_page_content',
    'access arguments' => array('use mobile adaptive'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function mobile_adaptive_permission() {
  $items = array();
  $items['use mobile adaptive'] = array(
    'title' => t('Use mobile adaptive'), 
    'description' => t('Perform testing of layout in mobile devices.'),
  );
  return $items;
}

function mobile_adaptive_init() {
  if (!user_access('use mobile adaptive')) {
		return;
  }
	// Add nesessary scripts and settings.
	$module_path = drupal_get_path('module', 'mobile_adaptive');
	$js_settings = array(
	  'mobile_adaptive_script_path' => $module_path . '/js',
	  'mobile_adaptive_path' => url('mobile-adaptive', array('query' => array('page_path' => $_GET['q']))),
	);
	drupal_add_js($js_settings, 'setting');
	drupal_add_css($module_path . '/js/mobile-adaptive.css');
	drupal_add_js($module_path . '/js/mobile_adaptive.js');
	drupal_add_js($module_path . '/js/rotate.js');

	// Check if it's mobile adaptive page and replace it with tested page.
	// It's important for browsers like FF, IE, which doesn't allow to view
	// current page in Iframe.
	if (mobile_adaptive_is_mobile_adaptive_page()) {
	  $_GET['q'] = $_GET['page_path'];
	}
}

function mobile_adaptive_is_mobile_adaptive_page() {
	return arg(0) == 'mobile-adaptive';
}