<?php

/**
* Implements hook_help().
*/
function xiaozhushou_tigtag_help($path, $arg) {
  if ($path == 'admin/help#xiaozhushou_tigtag') {
    return t('Scrape content from Tigtag');
  }
}

/**
 * Implements hook_init()
 */
function xiaozhushou_tigtag_init() {
  module_load_include('inc', 'xiaozhushou_utilities', 'includes/Utility.class');
  
  $util = Utility::getInstance();
  $util->loadSettings('xiaozhushou_tigtag');
}
