<?php

/**
* Implements hook_help().
*/
function xiaozhushou_sydneytoday_help($path, $arg) {
  if ($path == 'admin/help#xiaozhushou_sydneytoday') {
    return t('Scrape content from Sydneytoday');
  }
}

/**
 * Implements hook_init()
 */
function xiaozhushou_sydneytoday_init() {
  module_load_include('inc', 'xiaozhushou_utilities', 'includes/Utility.class');
  
  $util = Utility::getInstance();
  $util->loadSettings('xiaozhushou_sydneytoday');
  
  module_load_include('inc', 'xiaozhushou_sydneytoday', 'includes/sydneytoday');
}

/**
 * Implements hook_cron_queue_info()
 */
function xiaozhushou_sydneytoday_cron_queue_info() {
  // cron task to craw rental list
  $queues['sydneytoday_rental_list_craw'] = array(
    'worker callback' => 'sydneytoday_rental_list_craw',
    // 'time' => 30,
  );
  
  // cron task to craw rental item details
  $queues['sydneytoday_rental_item_parse'] = array(
    'worker callback' => 'sydneytoday_rental_item_parse',
  );
  
  // cron task to import rental items as Drupal nodes
  $queues['sydneytoday_rental_item_import'] = array(
    'worker callback' => 'sydneytoday_rental_item_import',
  );
  
  return $queues;
}

/**
 * Implements hook_cron()
 */
function xiaozhushou_sydneytoday_cron() {
  // add a list craw cron job to the queue
  $queue_list = DrupalQueue::get('sydneytoday_rental_list_craw');
  $queue_list->createItem(null);
  
  // craw items details
  $items = db_select('xiaozhushou_sydneytoday_rental_item', 'ri')
    ->fields('ri')
    ->condition('crawed', 0)
    ->execute();
  
  while ($item = $items->fetchAssoc()) {
    $queue_item = DrupalQueue::get('sydneytoday_rental_item_parse');
    $queue_item->createItem($item);
    // set to crawed
    $query = db_update('xiaozhushou_sydneytoday_rental_item')
      ->fields(array('crawed' => 1))
      ->condition('id', $item['id'])
      ->execute();
  }
  
  // import items to Drupal as nodes
  $items = db_select('xiaozhushou_sydneytoday_rental_item', 'ri')
    ->fields('ri')
    ->condition('imported', 0)
    ->execute();
  
  while ($item = $items->fetchAssoc()) {
    $queue_item = DrupalQueue::get('sydneytoday_rental_item_import');
    $queue_item->createItem($item);
    // set to imported
    $query = db_update('xiaozhushou_sydneytoday_rental_item')
      ->fields(array('imported' => 1))
      ->condition('id', $item['id'])
      ->execute();
  }
}