<?php

/**
* Implements hook_help().
*/
function xiaozhushou_sydneytoday_help($path, $arg) {
  if ($path == 'admin/help#xiaozhushou_sydneytoday') {
    return t('Scrape content from Sydneytoday');
  }
}

/**
 * Implements hook_init()
 */
function xiaozhushou_sydneytoday_init() {
  module_load_include('inc', 'xiaozhushou_utilities', 'includes/Utility.class');
  
  $util = Utility::getInstance();
  $util->loadSettings('xiaozhushou_sydneytoday');
  
  module_load_include('inc', 'xiaozhushou_sydneytoday', 'includes/sydneytoday');
}

/**
 * Implements hook_cron_queue_info()
 */
function xiaozhushou_sydneytoday_cron_queue_info() {
  // cron task to craw rental list
  $queues['sydneytoday_rental_list_craw'] = array(
    'worker callback' => 'sydneytoday_rental_list_craw',
    // 'time' => 30,
  );
  
  // cron task to parse rental items as Drupal nodes
  $queues['sydneytoday_rental_item_parse'] = array(
    'worker callback' => 'sydneytoday_rental_item_parse',
  );
  
  return $queues;
}

/**
 * Implements hook_cron()
 */
function xiaozhushou_sydneytoday_cron() {
  $my_queue = DrupalQueue::get('sydneytoday_rental_list_craw');
  $my_queue->createItem(null);
  
}