<?php

/**
* Implements hook_help().
*/
function xiaozhushou_tigtag_user_help($path, $arg) {
  if ($path == 'admin/help#xiaozhushou_tigtag_user') {
    return t('User registeration and management');
  }
}

/**
 * Implements hook_init()
 */
function xiaozhushou_tigtag_user_init() {
  module_load_include('inc', 'xiaozhushou_utilities', 'includes/Utility.class');
  
  $util = Utility::getInstance();
  $util->loadSettings('xiaozhushou_tigtag_user');
}

/**
 * Implements hook_menu()
 * @return string
 */
function xiaozhushou_tigtag_user_menu() {
//  module_load_include('inc', 'xiaozhushou_tigtag_user', 'includes/tigtag_user_list');
  
  $items = array();
  
  $items['admin/config/xiaozhushou/tigtag'] = array(
    'title' => 'Tigtag settings',
    'description' => 'All Tigtag settings',
    'weight' => 0,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access xiaozhushou settings'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  
  $items['admin/config/xiaozhushou/tigtag/user'] = array(
    'title' => 'Tigtag user settings',
    'description' => 'Administer Tigtag users.',
    'page callback' => 'tigtag_user_overview',
    'access arguments' => array('access xiaozhushou settings'),
    'file' => 'includes/tigtag_user.inc',
    'weight' => -10,
  );
  
  $items['admin/config/xiaozhushou/tigtag/user/%/check'] = array(
    'title' => 'User validation',
    'page callback' => 'tigtag_user_check',
    'page arguments' => array(5),
    'access arguments' => array('access xiaozhushou settings'),
    'file' => 'includes/tigtag_user.inc',
  );
  
  $items['admin/config/xiaozhushou/tigtag/user/%/promote'] = array(
    'title' => 'User promotion',
    'page callback' => 'tigtag_user_promote',
    'page arguments' => array(5),
    'access arguments' => array('access xiaozhushou settings'),
    'file' => 'includes/tigtag_user.inc',
  );
  
  $items['admin/config/xiaozhushou/tigtag/user/%/refresh'] = array(
    'title' => 'User refresh (delete cookie)',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tigtag_user_refresh' ,5),
    'access arguments' => array('access xiaozhushou settings'),
    'file' => 'includes/tigtag_user.inc',
  );
  
  $items['admin/config/xiaozhushou/tigtag/user/%/delete'] = array(
    'title' => 'User deletion',
    'page callback' => 'tigtag_user_delete',
    'page arguments' => array(5),
    'access arguments' => array('access xiaozhushou settings'),
    'file' => 'includes/tigtag_user.inc',
  );

  $items['admin/config/xiaozhushou/tigtag/user/list'] = array(
    'title' => 'List',
    'weight' => 0,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/config/xiaozhushou/tigtag/user/register'] = array(
    'title' => 'Register Tigtag user',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tigtag_user_register'),
    'access arguments' => array('access xiaozhushou settings'),
    'file' => 'includes/tigtag_user.inc',
    'type' => MENU_LOCAL_TASK
  );
  return $items;

}

/**
 * Implements hook_tigtag_user_operations()
 */
function xiaozhushou_tigtag_user_tigtag_user_operations($form = array(), $form_state = array()) {
  $operations = array(
    'delete' => array(
      'label' => t('Delete the selected users'),
      'callback' => 'tigtag_user_operations_delete',
    ),
  );
  return $operations;
}

/**
 * Delete a Tigtag user account
 */
function tigtag_user_operations_delete() {
  die('delete me');
}

/**
 * Implements hook_theme()
 */
//function xiaozhushou_tigtag_user_theme($existing, $type, $theme, $path) {
//  
//}