<?php

/**
* Implements hook_help().
*/
function xiaozhushou_tigtag_user_help($path, $arg) {
  if ($path == 'admin/help#xiaozhushou_tigtag_user') {
    return t('User registeration and management');
  }
}

/**
 * Implements hook_init()
 */
function xiaozhushou_tigtag_user_init() {
  module_load_include('inc', 'xiaozhushou_utilities', 'includes/Utility.class');
  
  $util = Utility::getInstance();
  $util->loadSettings('xiaozhushou_tigtag_user');
}

/**
 * Implements hook_permission()
 */
function xiaozhushou_tigtag_user_permission() {
  return array(
    'view tigtag user list' => array(
      'title' => t('View Tigtag user list'),
      'description' => t('Be able to administer Tigtag user list'),
    ),
  );
}

/**
 * Implements hook_menu()
 * @return string
 */
function xiaozhushou_tigtag_user_menu() {
//  module_load_include('inc', 'xiaozhushou_tigtag_user', 'includes/tigtag_user_list');
  
  $items = array();

  $items['admin/config/xiaozhushou/tigtag/user/list'] = array(
    'title' => 'Available Tigtag users',
    'description' => 'This page lists all available Tigtag Users.',
    'page callback' => '_tigtag_user_list',
    'access arguments' => array('view tigtag user list'),
    'weight' => -50,
    'file' => 'includes/tigtag_user_list.inc',
  );
  
  return $items;
}
